# Generated by Django 3.1 on 2021-03-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210314_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
