# Generated by Django 3.1 on 2021-03-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210314_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
