# Generated by Django 3.1 on 2021-03-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210314_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
