# Generated by Django 3.1 on 2021-03-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210316_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_meme',
        ),
    ]
