# Generated by Django 3.2.6 on 2022-07-10 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 10, 21, 1, 7, 490697, tzinfo=utc)),
        ),
    ]
